#IP da Central de Alarme
alarm_addr: 192.168.x.x

#Porta da Central de Alarme (padrão: 9009)
alarm_port: 9009

#Senha da Central de Alarme
alarm_passwd: 1234

#IP/Host do servidor MQTT
mqtt_addr: 192.168.x.x

#Porta do servidor MQTT
mqtt_port: 1883

#Usuário MQTT
mqtt_user: usuario

#Senha MQTT
mqtt_passwd: senha

#De quanto em quanto tempo o status da central vai ser enviado (em segundos)
send_status_interval: 10

#Tópico MQTT que a mensagem de status do alarme será enviado
mqtt_topic_alarm_status: "alarm/status"

#Tópico MQTT para escutar os controles
mqtt_topic_alarm_control: "alarm/control"